### ISSUE TITLE
Misaligned image on mobile

### ISSUE THREAD

**Issue by iliyaM** [Way2CU/Banana-Site#9]
![screenshot from 2017-05-03 14-11-34](https://cloud.githubusercontent.com/assets/20294485/25658227/806d4450-300a-11e7-8c54-b31a419c0894.png)

**Comment by MeanEYE** [comment]
Is this on desktop version or mobile?

**Comment by iliyaM** [comment]
mobile

**Comment by MeanEYE** [comment]
Most likely from `translateX`. I don't distinctly remember changes that removed some of the gallery behavior.

**Comment by iliyaM** [comment]
The image had a right: 0; coming from somewhere i count not find from where.
so i did right: auto !important. and that solved the problem.
